spring:
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username:
    password:
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

  configuration:
    lazyLoadingEnabled: true
    aggressiveLazyLoading: false
    mapUnderscoreToCamelCase: true



logging:
  level:
    com:
      api:
        devtest: debug
